require("dplyr")
require("lubridate")
Power<-read.table("household_power_consumption.txt",na.strings = "?",header = TRUE,sep = ";")
datetime <- dmy_hms(paste(Power$Date, Power$Time))
Power<-cbind(datetime,Power)
Power$Date<-as.Date(Power$Date,format="%d/%m/%Y")
Subset<-filter(Power,Date=="2007-02-01"|Date=="2007-02-02")
png("plot2.png")
plot(Global_active_power~datetime,data=Subset,ylab="Global Active Power (kilowatts)",type="l")
dev.off()
